In [ ]:
# from my_func import *
import pandas as pd
import numpy as np
import os

In [ ]:
parquet_list = os.listdir('/Users/packchansaem/Desktop/project/maket_kurly/parquet_data/')
parquet_list.sort()
parquet_list

['.DS_Store',
 'AT_TSALET_ALL_201601.parquet',
 'AT_TSALET_ALL_201602.parquet',
 'AT_TSALET_ALL_201603.parquet',
 'AT_TSALET_ALL_201604.parquet',
 'AT_TSALET_ALL_201605.parquet',
 'AT_TSALET_ALL_201606.parquet',
 'AT_TSALET_ALL_201607.parquet',
 'AT_TSALET_ALL_201608.parquet',
 'AT_TSALET_ALL_201609.parquet',
 'AT_TSALET_ALL_201610.parquet',
 'AT_TSALET_ALL_201611.parquet',
 'AT_TSALET_ALL_201612.parquet',
 'AT_TSALET_ALL_201701.parquet',
 'AT_TSALET_ALL_201702.parquet',
 'AT_TSALET_ALL_201703.parquet',
 'AT_TSALET_ALL_201704.parquet',
 'AT_TSALET_ALL_201705.parquet',
 'AT_TSALET_ALL_201706.parquet',
 'AT_TSALET_ALL_201707.parquet',
 'AT_TSALET_ALL_201708.parquet',
 'AT_TSALET_ALL_201709.parquet',
 'AT_TSALET_ALL_201710.parquet',
 'AT_TSALET_ALL_201711.parquet',
 'AT_TSALET_ALL_201712.parquet',
 'AT_TSALET_ALL_201801.parquet',
 'AT_TSALET_ALL_201802.parquet',
 'AT_TSALET_ALL_201803.parquet',
 'AT_TSALET_ALL_201804.parquet',
 'AT_TSALET_ALL_201805.parquet',
 'AT_TSALET_ALL_201806.parquet',
 'AT_TSALET_ALL_201807.parquet',
 'AT_TSALET_ALL_201808.parquet',
 'AT_TSALET_ALL_201809.parquet',
 'AT_TSALET_ALL_201810.parquet',
 'AT_TSALET_ALL_201811.parquet',
 'AT_TSALET_ALL_201812.parquet',
 'AT_TSALET_ALL_201901.parquet',
 'AT_TSALET_ALL_201902.parquet',
 'AT_TSALET_ALL_201903.parquet',
 'AT_TSALET_ALL_201904.parquet',
 'AT_TSALET_ALL_201905.parquet',
 'AT_TSALET_ALL_201906.parquet',
 'AT_TSALET_ALL_201907.parquet',
 'AT_TSALET_ALL_201908.parquet',
 'AT_TSALET_ALL_201909.parquet',
 'AT_TSALET_ALL_201910.parquet',
 'AT_TSALET_ALL_201911.parquet',
 'AT_TSALET_ALL_201912.parquet',
 'AT_TSALET_ALL_202001.parquet',
 'AT_TSALET_ALL_202002.parquet',
 'AT_TSALET_ALL_202003.parquet',
 'AT_TSALET_ALL_202004.parquet',
 'AT_TSALET_ALL_202005.parquet',
 'AT_TSALET_ALL_202006.parquet',
 'AT_TSALET_ALL_202007.parquet',
 'AT_TSALET_ALL_202008.parquet',
 'AT_TSALET_ALL_202009.parquet']

In [ ]:
parquet_list.pop(0)

'.DS_Store'

In [ ]:
a_list = ['무', '배추', '대파', '건고추', '마늘', '양파','사과']
df_total = pd.DataFrame()
for i in parquet_list:
    df = pd.read_parquet(f'parquet_data/{i}')
    selcet_df=df[df['PUM_NM'].apply(lambda x: x in a_list)]
    df_total = pd.concat([df_total,selcet_df],axis=0)

In [ ]:
df_total

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
78,20160109,부산엄궁도매,부산청과,대파,대파(일반),kg,단,.,보통,부산 중구,1.0,100.0,1610.0,100.0,161000.0
79,20160109,부산엄궁도매,부산청과,대파,대파(일반),kg,단,.,보통,부산 중구,1.0,100.0,1610.0,100.0,161000.0
80,20160109,부산엄궁도매,부산청과,대파,대파(일반),kg,단,.,보통,부산 중구,1.0,100.0,1610.0,100.0,161000.0
81,20160109,부산엄궁도매,부산청과,대파,대파(일반),kg,단,.,보통,부산 중구,1.0,100.0,1610.0,100.0,161000.0
82,20160109,부산엄궁도매,부산청과,대파,대파(일반),kg,단,.,보통,부산 중구,1.0,100.0,1610.0,100.0,161000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3453589,20200928,인천구월도매,인천농산물,사과,홍로,kg,상자,.,상,충청남도 당진군,5.0,48.0,26000.0,240.0,1248000.0
3453590,20200928,인천구월도매,인천농산물,사과,홍로,kg,상자,.,상,충청남도 당진군,5.0,32.0,33000.0,160.0,1056000.0
3453591,20200928,인천구월도매,인천농산물,사과,홍로,kg,상자,.,상,충청남도 당진군,5.0,3.0,39000.0,15.0,117000.0
3453597,20200928,인천구월도매,인천농산물,사과,양광,kg,상자,.,상,경상북도 영주시,15.0,1.0,24000.0,15.0,24000.0
3453744,20200928,서울강서도매,강서청과,무,기타무,kg,.,2개,.,광주 북구,20.0,42.0,17000.0,840.0,714000.0

In [ ]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18984089 entries, 78 to 3453744
Data columns (total 15 columns):
 #   Column    Dtype
---  ------    -----
 0   SALEDATE  int64
 1   WHSAL_NM  object
 2   CMP_NM    object
 3   PUM_NM    object
 4   KIND_NM   object
 5   DAN_NM    object
 6   POJ_NM    object
 7   SIZE_NM   object
 8   LV_NM     object
 9   SAN_NM    object
 10  DANQ      float64
 11  QTY       float64
 12  COST      float64
 13  TOT_QTY   float64
 14  TOT_AMT   float64
dtypes: float64(5), int64(1), object(9)
memory usage: 2.3+ GB

In [ ]:
#메모리 최소화를 위해 카테고리 타입으로 변경
df_total=df_total.astype({'KIND_NM':'category','CMP_NM':'category','LV_NM':'category','SAN_NM':'category','PUM_NM':'category'})
df_total=df_total.astype({'WHSAL_NM':'category','DAN_NM':'category','POJ_NM':'category','SIZE_NM':'category'})

#결측치 채우기
df_total['LV_NM']=df_total['LV_NM'].fillna('.')
df_total['POJ_NM']=df_total['POJ_NM'].fillna('.')
df_total['SIZE_NM']=df_total['SIZE_NM'].fillna('.')
df_total['SAN_NM']=df_total['SAN_NM'].astype('object')
df_total['SAN_NM']=df_total['SAN_NM'].fillna('.')
df_total['SAN_NM']=df_total['SAN_NM'].astype('category')
df_total['DAN_NM']=df_total['DAN_NM'].fillna('.')

#데이터타입을 datetime으로 변경
df_total["SALEDATE"] = pd.to_datetime( df_total["SALEDATE"], format='%Y%m%d' )

#거래가 취소되거나 거래량이 0인 경우 드랍
df_total=df_total.drop(df_total[df_total['TOT_QTY']<=0].index)
df_total=df_total.drop(df_total[df_total['TOT_AMT']<=0].index)

#index 정렬
df_total = df_total.sort_values('SALEDATE').reset_index(drop=True)

In [ ]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18407168 entries, 0 to 18407167
Data columns (total 15 columns):
 #   Column    Dtype
---  ------    -----
 0   SALEDATE  datetime64[ns]
 1   WHSAL_NM  category
 2   CMP_NM    category
 3   PUM_NM    category
 4   KIND_NM   category
 5   DAN_NM    category
 6   POJ_NM    category
 7   SIZE_NM   category
 8   LV_NM     category
 9   SAN_NM    category
 10  DANQ      float64
 11  QTY       float64
 12  COST      float64
 13  TOT_QTY   float64
 14  TOT_AMT   float64
dtypes: category(9), datetime64[ns](1), float64(5)
memory usage: 1.0 GB

In [ ]:
df_total.to_parquet('new_total_df2.parquet', engine="pyarrow", compression='gzip')